# Generated by Django 5.1.4 on 2024-12-21 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(),
        ),
    ]
